# Generated by Django 5.0.3 on 2024-08-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHWEB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
