# Generated by Django 5.0.3 on 2024-08-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHWEB', '0003_chef_waiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('bg', models.ImageField(upload_to='')),
            ],
        ),
    ]
