# Generated by Django 5.1 on 2024-08-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHWEB', '0004_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('food_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='event_description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='events',
            name='event_img',
            field=models.ImageField(default='img.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
