# Generated by Django 5.1 on 2024-08-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHWEB', '0005_about_special_events_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='pic',
            field=models.ImageField(default='img.png', upload_to=''),
        ),
    ]
