# Generated by Django 5.1 on 2024-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHWEB', '0007_book_comment_contact_special_description1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='pic',
            field=models.ImageField(default='img.png, img.jpg', upload_to=''),
        ),
    ]
