# Generated by Django 5.1 on 2024-08-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHWEB', '0008_alter_special_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='pic',
            field=models.ImageField(default='img.jpg', upload_to=''),
        ),
    ]
