# Generated by Django 5.1 on 2024-08-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHWEB', '0010_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='second_title',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
