# Generated by Django 5.1 on 2024-08-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHWEB', '0011_special_second_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='second_pic',
            field=models.ImageField(default='img.jpg', upload_to=''),
        ),
    ]
